# Generated by Django 5.1.5 on 2025-01-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(max_length=40)),
                ("Email", models.EmailField(blank=True, max_length=254, null=True)),
                ("Contact", models.IntegerField()),
                ("Notes", models.TextField(blank=True, max_length=250, null=True)),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Amount", models.IntegerField(blank=True, default=0)),
                ("Due", models.DateTimeField(blank=True, null=True)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Paying", "Paying"),
                            ("Paid", "Paid"),
                            ("Not Paid", "Not Paid"),
                        ],
                        default="Not Paid",
                        max_length=13,
                    ),
                ),
                ("Received", models.IntegerField(blank=True, default=0)),
                ("Notes", models.TextField(blank=True, max_length=30, null=True)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="debts.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebtInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Amount", models.IntegerField(blank=True, default=0)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Debt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="debts.debt",
                    ),
                ),
            ],
        ),
    ]
