# Generated by Django 5.1.6 on 2025-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="Notes",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
