# Generated by Django 5.1.6 on 2025-04-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_alter_debt_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Contact',
            field=models.CharField(max_length=13),
        ),
    ]
