# Generated by Django 5.1.6 on 2025-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="Contact",
            field=models.CharField(),
        ),
    ]
