# Generated by Django 5.1.6 on 2025-06-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_business_email'),
        ('credits', '0002_alter_supplier_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice', models.CharField(choices=[('All', 'All'), ('Current', 'Current')], default='This Month', max_length=11)),
                ('Business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.business')),
                ('Cashier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
