# Generated by Django 5.1.6 on 2025-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="Name",
            field=models.CharField(
                choices=[
                    ("Bronze", "Bronze"),
                    ("Silver", "Silver"),
                    ("Gold", "Gold"),
                    ("Diamond", "Diamond"),
                ],
                default="Bronze",
                max_length=10,
            ),
        ),
    ]
