# Generated by Django 5.1.6 on 2025-04-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='Name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Advanced', 'Advanced'), ('Premium', 'Premium')], default='Bronze', max_length=20),
        ),
    ]
