# Generated by Django 5.1.6 on 2025-06-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAsYouEarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatePaid', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(blank=True, default='PAYE', max_length=50)),
                ('Notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresumptiveTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatePaid', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(blank=True, default='Presumptive', max_length=50)),
                ('Notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayAsYouEarnThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Threshold', models.IntegerField(default=0)),
                ('Percentage', models.IntegerField(default=0)),
                ('Tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.payasyouearn')),
            ],
        ),
        migrations.CreateModel(
            name='PresumptiveTaxThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.IntegerField(default=0)),
                ('To', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(default=0)),
                ('Tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.presumptivetax')),
            ],
        ),
    ]
