# Generated by Django 5.1.6 on 2025-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_payasyouearn_presumptivetax_payasyouearnthreshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payasyouearn',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='presumptivetax',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
