# Generated by Django 5.1.6 on 2025-06-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_payasyouearn_status_presumptivetax_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payasyouearn',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='presumptivetax',
            old_name='status',
            new_name='Status',
        ),
    ]
