# Generated by Django 5.1.6 on 2025-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_status_payasyouearn_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payasyouearn',
            name='Notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='presumptivetax',
            name='Notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
