# Generated by Django 5.1.6 on 2025-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_payasyouearn_notes_alter_presumptivetax_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueAddedTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(blank=True, default='VAT', max_length=50)),
                ('Status', models.BooleanField(blank=True, default=True)),
                ('Threshold', models.IntegerField(default=0)),
                ('Rate', models.IntegerField(default=16.5)),
            ],
        ),
        migrations.RenameField(
            model_name='payasyouearn',
            old_name='DatePaid',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='presumptivetax',
            old_name='DatePaid',
            new_name='Date',
        ),
    ]
