# Generated by Django 5.1.6 on 2025-06-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_valueaddedtax_rename_datepaid_payasyouearn_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(blank=True, default='PAYE', max_length=50)),
                ('Notes', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Status', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTaxThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Threshold', models.IntegerField(default=0)),
                ('Percentage', models.IntegerField(default=0)),
                ('Tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.incometax')),
            ],
        ),
    ]
