# Generated by Django 5.1.6 on 2025-09-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_profile_about'),
        ('management', '0009_incometax_incometaxthreshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermAndConditionsAgreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.business')),
            ],
        ),
    ]
