# Generated by Django 5.1.5 on 2025-01-20 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0001_initial"),
        ("credits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(max_length=20)),
                ("Price", models.IntegerField()),
                ("Quantity", models.IntegerField(default=1)),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Operational", "Operational"),
                            ("Payroll", "Payroll"),
                            ("Stock", "Stock"),
                            ("Asset", "Asset"),
                        ],
                        default="Operational Expense",
                        max_length=20,
                    ),
                ),
                (
                    "PMode",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Credit", "Credit")],
                        default="Cash",
                        max_length=7,
                    ),
                ),
                ("Discount", models.BooleanField(default=0)),
                ("Notes", models.TextField(default="non", max_length=150)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Credit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="credits.credit",
                    ),
                ),
                (
                    "Supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="credits.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("OriginalPrice", models.IntegerField()),
                ("DiscountPrice", models.IntegerField()),
                ("Notes", models.TextField(default="non", max_length=30)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(max_length=20)),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Operational", "Operational"),
                            ("Payroll", "Payroll"),
                            ("Stock", "Stock"),
                            ("Asset", "Asset"),
                        ],
                        default="Operational Expense",
                        max_length=20,
                    ),
                ),
                (
                    "Interval",
                    models.CharField(
                        blank=True,
                        choices=[("Cash", "Cash"), ("Credit", "Credit")],
                        default="Monthly",
                        max_length=9,
                    ),
                ),
                ("AutoRecord", models.BooleanField(blank=True, default=False)),
                ("Notes", models.TextField(default="non", max_length=150)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="ExpenseAccount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="expenses.expenseaccount",
            ),
        ),
        migrations.CreateModel(
            name="BufferExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Operational", "Operational"),
                            ("Payroll", "Payroll"),
                            ("Stock", "Stock"),
                            ("Asset", "Asset"),
                        ],
                        default="Operational",
                        max_length=20,
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Quantity", models.IntegerField(default=1)),
                ("Price", models.IntegerField()),
                (
                    "PMode",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Credit", "Credit")],
                        default="Cash",
                        max_length=7,
                    ),
                ),
                ("Discount", models.BooleanField(default=False)),
                ("Notes", models.TextField(default="non", max_length=150)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ExpenseAccount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="expenses.expenseaccount",
                    ),
                ),
            ],
        ),
    ]
