# Generated by Django 5.1.6 on 2025-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensesgeneralcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Notes',
            field=models.TextField(blank=True, default='non', max_length=150, null=True),
        ),
    ]
