# Generated by Django 5.1.6 on 2025-06-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_threshold_tax_delete_tax_delete_threshold'),
        ('expenses', '0003_alter_expense_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.salary'),
        ),
    ]
