# Generated by Django 5.1.5 on 2025-01-20 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(max_length=40)),
                ("InitialValue", models.IntegerField(default=0)),
                ("CurrentValue", models.IntegerField(default=0)),
                ("DepreciationRate", models.IntegerField(default=0)),
                ("AnnualDepreciation", models.IntegerField(default=0)),
                ("SalvageValue", models.IntegerField(default=0)),
                ("UsefulLife", models.IntegerField(default=0)),
                ("Notes", models.TextField(default="non", max_length=200)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "TaxYear",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.taxyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Photo", models.ImageField(upload_to="asset")),
                (
                    "Asset",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.assets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetsBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=25)),
                ("Quantity", models.IntegerField(default=1)),
                ("InitialValue", models.IntegerField()),
                (
                    "Acquired_through",
                    models.CharField(
                        choices=[
                            ("Purchase(cash)", "Purchase(cash)"),
                            ("Purchase(debts)", "Purchase(debts)"),
                            ("Donation", "Donation"),
                        ],
                        default="Purchase(cash)",
                        max_length=18,
                    ),
                ),
                ("SalvageValue", models.IntegerField(default=0)),
                ("UsefulLife", models.IntegerField(default=0)),
                ("Notes", models.TextField(default="non", max_length=30)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Title", models.CharField(max_length=20)),
                ("Description", models.TextField(default="", max_length=100)),
                (
                    "Asset",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.assets",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shareholders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Value", models.IntegerField(default=0)),
                ("Shares", models.IntegerField(default=0)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
