# Generated by Django 5.1.6 on 2025-03-06 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0006_salary_taxaccountthisyear"),
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CatalogueGroup",
            new_name="CatalogueCategories",
        ),
        migrations.RenameModel(
            old_name="GroupProduct",
            new_name="CatalogueProduct",
        ),
        migrations.RenameModel(
            old_name="GroupProductFeature",
            new_name="CatalogueProductFeature",
        ),
        migrations.RenameModel(
            old_name="GroupProductPhoto",
            new_name="CatalogueProductPhoto",
        ),
        migrations.RemoveField(
            model_name="buffergroupproductphoto",
            name="Product",
        ),
        migrations.RemoveField(
            model_name="buffergroupproductfeature",
            name="Business",
        ),
        migrations.RemoveField(
            model_name="buffergroupproductphoto",
            name="Business",
        ),
        migrations.DeleteModel(
            name="BufferGroupProduct",
        ),
        migrations.DeleteModel(
            name="BufferGroupProductFeature",
        ),
        migrations.DeleteModel(
            name="BufferGroupProductPhoto",
        ),
    ]
