# Generated by Django 5.1.5 on 2025-01-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0001_initial"),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Notes", models.CharField(max_length=200, null=True)),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(max_length=30)),
                ("InitialQuantity", models.IntegerField(default=0)),
                ("Cost", models.IntegerField(default=0)),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
                (
                    "Expenses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(max_length=30)),
                ("Brand", models.CharField(max_length=30)),
                ("Size", models.CharField(max_length=15)),
                ("ExpiryDate", models.DateTimeField(null=True)),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventorycategory",
                    ),
                ),
                (
                    "Expenses",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expenses.expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Code", models.CharField(default="", max_length=30)),
                ("Location", models.CharField(max_length=30, null=True)),
                ("Cost", models.IntegerField(default=0)),
                ("BPrice", models.IntegerField(default=0)),
                ("SPrice", models.IntegerField(default=0)),
                ("InitialQuantity", models.IntegerField(default=0)),
                ("CurrentQuantity", models.IntegerField(default=0)),
                ("InitialValue", models.IntegerField(default=0)),
                ("CurrentValue", models.IntegerField(default=0)),
                ("ReorderPerc", models.IntegerField(default=50)),
                ("Close", models.BooleanField(default=False)),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
                (
                    "Product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryproduct",
                    ),
                ),
            ],
        ),
    ]
