# Generated by Django 5.1.5 on 2025-01-20 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("User", "0001_initial"),
        ("debts", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="bufferIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Code", models.CharField(default="", max_length=30)),
                ("Amount", models.IntegerField()),
                ("Quantity", models.IntegerField(default=1)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.inventoryproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Notes", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Receiver", models.CharField(default="", max_length=100)),
                ("Date", models.DateTimeField(null=True)),
                ("OrderNumber", models.IntegerField(default=0)),
                ("DispatchDate", models.DateTimeField(null=True)),
                ("ValidityLimit", models.DateTimeField(null=True)),
                ("GrandTotal", models.IntegerField(default=0)),
                ("VAT", models.FloatField(default=0)),
                ("SubTotal", models.IntegerField(default=0)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Item", models.CharField(default="", max_length=30)),
                ("UnitPrice", models.IntegerField()),
                ("Total", models.IntegerField()),
                ("Quantity", models.IntegerField(default=1)),
                (
                    "invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="income.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(default="", max_length=50)),
                ("Price", models.IntegerField(blank=True, default=0)),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="income.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductGeneralContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Choice",
                    models.CharField(
                        choices=[
                            ("This Year", "This Year"),
                            ("This Month", "This Month"),
                        ],
                        default="This Month",
                        max_length=11,
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(null=True)),
                ("Code", models.CharField(default="", max_length=30)),
                ("Amount", models.IntegerField()),
                ("Quantity", models.IntegerField(default=1)),
                (
                    "PMode",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Credit", "Credit")],
                        default="Cash",
                        max_length=7,
                    ),
                ),
                ("Discount", models.BooleanField(blank=True, default=False)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Debt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="debts.debt",
                    ),
                ),
                (
                    "Product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inventory.inventoryproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(default="", max_length=50)),
                ("Description", models.TextField(max_length=200)),
                (
                    "ChargingCriteria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("per specified duration", "per specified duration"),
                            ("per srvice", "per service"),
                            ("agreed condition", "agreed condition"),
                        ],
                        default="per service",
                        max_length=25,
                    ),
                ),
                ("Price", models.IntegerField(blank=True, default=0)),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="income.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                (
                    "Package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="income.package",
                    ),
                ),
                (
                    "Service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="income.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceAnnualContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Choice",
                    models.CharField(
                        choices=[
                            ("Categories", "Categories"),
                            ("Service", "Service"),
                            ("Packages", "Packages"),
                        ],
                        default="Service/Packages",
                        max_length=17,
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Amount", models.IntegerField(default=0)),
                (
                    "PMode",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Credit", "Credit")],
                        default="Cash",
                        max_length=7,
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceBufferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Buffer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="income.servicebuffer",
                    ),
                ),
                (
                    "Package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="income.package",
                    ),
                ),
                (
                    "Service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="income.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceGeneralContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Choice",
                    models.CharField(
                        choices=[
                            ("This Year", "This Year"),
                            ("This Month", "This Month"),
                        ],
                        default="This Month",
                        max_length=11,
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Amount", models.IntegerField(default=0)),
                (
                    "PMode",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Credit", "Credit")],
                        default="Cash",
                        max_length=7,
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="debts.customer",
                    ),
                ),
                (
                    "Debt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="debts.debt",
                    ),
                ),
                (
                    "Package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="income.package",
                    ),
                ),
                (
                    "Service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="income.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceMonthlyContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Choice",
                    models.CharField(
                        choices=[
                            ("Categories", "Categories"),
                            ("Service", "Service"),
                            ("Packages", "Packages"),
                        ],
                        default="Service/Packages",
                        max_length=17,
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
