# Generated by Django 5.1.5 on 2025-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productincome",
            name="Date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
