# Generated by Django 5.1.6 on 2025-02-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0002_alter_productincome_date"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitems",
            name="Item",
        ),
        migrations.AddField(
            model_name="invoiceitems",
            name="Product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="inventory.inventoryproduct",
            ),
        ),
    ]
