# Generated by Django 5.1.6 on 2025-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0003_remove_invoiceitems_item_invoiceitems_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="Status",
            field=models.BooleanField(null=True),
        ),
    ]
