# Generated by Django 5.1.6 on 2025-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0004_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="Status",
            field=models.BooleanField(default=True),
        ),
    ]
