# Generated by Django 5.1.6 on 2025-02-21 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debts", "0001_initial"),
        ("income", "0005_alter_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="Receiver",
        ),
        migrations.AddField(
            model_name="invoice",
            name="Customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="debts.customer",
            ),
        ),
    ]
