# Generated by Django 5.1.6 on 2025-02-21 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0006_remove_invoice_receiver_invoice_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="Customer",
            new_name="Receiver",
        ),
    ]
