# Generated by Django 5.1.6 on 2025-02-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0007_rename_customer_invoice_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="Date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
