# Generated by Django 5.1.6 on 2025-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0008_alter_invoice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="Status",
            field=models.BooleanField(default=False),
        ),
    ]
