# Generated by Django 5.1.6 on 2025-02-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0009_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebufferitem",
            name="Quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="serviceincome",
            name="Quantity",
            field=models.IntegerField(default=1),
        ),
    ]
