# Generated by Django 5.1.6 on 2025-02-27 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0010_servicebufferitem_quantity_serviceincome_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebuffer",
            name="Amount",
        ),
        migrations.RemoveField(
            model_name="servicebuffer",
            name="PMode",
        ),
        migrations.AddField(
            model_name="servicebuffer",
            name="Package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="income.package",
            ),
        ),
        migrations.AddField(
            model_name="servicebuffer",
            name="Service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="income.service",
            ),
        ),
        migrations.DeleteModel(
            name="ServiceBufferItem",
        ),
    ]
