# Generated by Django 5.1.6 on 2025-02-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0011_remove_servicebuffer_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebuffer",
            name="Quantity",
            field=models.IntegerField(default=1),
        ),
    ]
