# Generated by Django 5.1.6 on 2025-02-28 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0006_salary_taxaccountthisyear"),
        ("income", "0012_servicebuffer_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceIncomeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Amount", models.IntegerField(default=0)),
                (
                    "PMode",
                    models.CharField(
                        choices=[("Cash", "Cash"), ("Credit", "Credit")],
                        default="Cash",
                        max_length=7,
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.business"
                    ),
                ),
                (
                    "Cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
