# Generated by Django 5.1.6 on 2025-02-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0013_serviceincomereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebuffer",
            name="Report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="income.serviceincomereport",
            ),
        ),
    ]
