# Generated by Django 5.1.6 on 2025-02-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0014_servicebuffer_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceincomereport",
            old_name="Amount",
            new_name="Excess",
        ),
        migrations.AddField(
            model_name="serviceincomereport",
            name="Paid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="serviceincomereport",
            name="Total",
            field=models.IntegerField(default=0),
        ),
    ]
