# Generated by Django 5.1.6 on 2025-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0015_rename_amount_serviceincomereport_excess_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebuffer",
            name="Amount",
            field=models.IntegerField(default=1),
        ),
    ]
