# Generated by Django 5.1.6 on 2025-03-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0016_servicebuffer_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicebuffer",
            name="PMode",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Credit", "Credit")],
                default="Cash",
                max_length=7,
            ),
        ),
    ]
