# Generated by Django 5.1.6 on 2025-03-02 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0017_servicebuffer_pmode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicebuffer",
            name="Report",
        ),
        migrations.DeleteModel(
            name="ServiceIncomeReport",
        ),
    ]
