# Generated by Django 5.1.6 on 2025-03-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0018_remove_servicebuffer_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitems",
            name="Package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="income.package",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitems",
            name="Service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="income.service",
            ),
        ),
    ]
