# Generated by Django 5.1.6 on 2025-03-03 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0006_salary_taxaccountthisyear"),
        ("income", "0019_invoiceitems_package_invoiceitems_service"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="bufferIncome",
            new_name="IncomeBuffer",
        ),
    ]
