# Generated by Django 5.1.6 on 2025-05-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0020_rename_bufferincome_incomebuffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceincome',
            name='Discount',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
