# Generated by Django 5.1.5 on 2025-01-20 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_creation", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="/appdefaults/add-photo4.png",
                        upload_to="bprofile",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                (
                    "Type",
                    models.CharField(blank=True, default="Groceries", max_length=33),
                ),
                ("About", models.TextField(max_length=110)),
                ("Email", models.EmailField(max_length=254)),
                ("Contact1", models.IntegerField(blank=True, null=True)),
                ("Contact2", models.IntegerField(blank=True, null=True)),
                ("Address", models.CharField(max_length=150)),
                ("PostBox", models.CharField(default="", max_length=50)),
                ("City", models.CharField(max_length=50)),
                ("Country", models.CharField(max_length=50)),
                ("ZipCode", models.CharField(blank=True, max_length=50, null=True)),
                ("Instagram", models.URLField(blank=True, max_length=100, null=True)),
                ("Facebook", models.URLField(blank=True, max_length=100, null=True)),
                ("Linkedin", models.URLField(blank=True, max_length=100, null=True)),
                (
                    "Owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Value", models.IntegerField(default=0)),
                ("TotalShares", models.IntegerField(default=100)),
                ("PayoutRatio", models.IntegerField(default=20)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Capital", models.IntegerField(default=0)),
                ("StartBusinessYear", models.DateTimeField(blank=True, null=True)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_creation", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(max_length=40)),
                ("Description", models.TextField(max_length=300)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Position", models.CharField(default="", max_length=40)),
                ("Duty", models.CharField(default="", max_length=200)),
                (
                    "Interval",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Weekly", "Weekly"),
                            ("Daily", "Daily"),
                            ("Hourly", "Hourly"),
                            ("Agreed Condition", "Agreed Condition"),
                        ],
                        default="Monthly",
                        max_length=17,
                    ),
                ),
                ("Salary", models.IntegerField(default=0)),
                (
                    "AccessLevel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="User.department",
                    ),
                ),
                (
                    "User",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                (
                    "Interval",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Weekly", "Weekly"),
                            ("Daily", "Daily"),
                            ("Agreed Condition", "Agreed Condition"),
                        ],
                        max_length=17,
                    ),
                ),
                ("Amount", models.IntegerField(default=0)),
                (
                    "Employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_creation", models.DateTimeField(auto_now=True)),
                (
                    "Gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Female",
                        max_length=8,
                        null=True,
                    ),
                ),
                ("DOB", models.DateField(null=True)),
                ("photo", models.ImageField(null=True, upload_to="profile")),
                ("About", models.TextField(max_length=130, null=True)),
                ("Contact1", models.IntegerField(null=True)),
                ("Contact2", models.IntegerField(blank=True, null=True)),
                ("City", models.CharField(max_length=50, null=True)),
                ("Country", models.CharField(max_length=50, null=True)),
                ("Instagram", models.URLField(max_length=100, null=True)),
                ("Facebook", models.URLField(max_length=100, null=True)),
                ("Linkedin", models.URLField(max_length=100, null=True)),
                (
                    "Role",
                    models.CharField(
                        blank=True, default="Buyer", max_length=7, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Amount", models.IntegerField(default=0)),
                ("PAYE", models.IntegerField(default=0)),
                (
                    "Employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(blank=True, max_length=40)),
                (
                    "Interval",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        default="Monthly",
                        max_length=17,
                    ),
                ),
                ("Notes", models.TextField(default="non", max_length=200)),
                ("Close", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxAccountThisYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AccumulatedTotal", models.IntegerField(blank=True, default=0)),
                (
                    "TaxAccount",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.taxaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeIncentives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Name", models.CharField(max_length=30)),
                ("Amount", models.IntegerField(default=0)),
                ("PAYE", models.IntegerField(default=0)),
                (
                    "Employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.employee",
                    ),
                ),
                (
                    "TaxAccountThisYear",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.taxaccountthisyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Allowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Amount", models.IntegerField(default=0)),
                ("PAYE", models.IntegerField(default=0)),
                (
                    "EmployeeAllowance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.employeeallowance",
                    ),
                ),
                (
                    "TaxAccountThisYear",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.taxaccountthisyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxInstallments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                ("Amount", models.IntegerField()),
                (
                    "TaxAccountThisYear",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.taxaccountthisyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VATRate", models.FloatField(default=16.5)),
                ("ShowEstimates", models.BooleanField(default=0)),
                ("IncludeVAT", models.BooleanField(default=0)),
                ("IncludePAYE", models.BooleanField(default=0)),
                ("IncludePresumptiveTax", models.BooleanField(default=0)),
                ("IncludeIncomeTax", models.BooleanField(default=0)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TaxYearStart", models.DateTimeField(blank=True)),
                ("TaxYearEnd", models.DateTimeField(blank=True)),
                ("TotalTaxes", models.IntegerField(blank=True, default=0)),
                ("TotalPaid", models.IntegerField(blank=True, default=0)),
                (
                    "Business",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="taxaccountthisyear",
            name="TaxYear",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.taxyear",
            ),
        ),
    ]
