# Generated by Django 5.1.5 on 2025-01-21 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="date_of_creation",
            new_name="Date",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="photo",
            new_name="Photo",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="User",
        ),
    ]
