# Generated by Django 5.1.5 on 2025-01-21 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_rename_date_of_creation_profile_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="date_of_creation",
            new_name="Date",
        ),
        migrations.RenameField(
            model_name="business",
            old_name="photo",
            new_name="Photo",
        ),
    ]
