# Generated by Django 5.1.5 on 2025-01-29 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_rename_date_of_creation_business_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDashAnnualContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Choice",
                    models.CharField(
                        choices=[
                            ("Categories", "Categories"),
                            ("Service", "Service"),
                            ("Packages", "Packages"),
                        ],
                        default="Service/Packages",
                        max_length=17,
                    ),
                ),
                (
                    "Business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.business",
                    ),
                ),
                (
                    "Cashier",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
