# Generated by Django 5.1.5 on 2025-01-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0005_businessdashcontent_delete_businessdashannualcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="TaxAccountThisYear",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.taxaccountthisyear",
            ),
        ),
    ]
