# Generated by Django 5.1.6 on 2025-04-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0006_salary_taxaccountthisyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="Contact1",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="business",
            name="Contact2",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
