# Generated by Django 5.1.6 on 2025-04-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_profile_contact1_alter_profile_contact2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Contact1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='Contact2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Contact1',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Contact2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
