# Generated by Django 5.1.6 on 2025-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_business_facebook_alter_business_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Email',
            field=models.CharField(),
        ),
    ]
