# Generated by Django 5.1.6 on 2025-04-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_business_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
