# Generated by Django 5.1.6 on 2025-06-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0014_tax"),
    ]

    operations = [
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Threshold", models.IntegerField(default=0)),
                ("Percentage", models.IntegerField(default=0)),
                (
                    "Tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.tax"
                    ),
                ),
            ],
        ),
    ]
