# Generated by Django 5.1.6 on 2025-06-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='Tax',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
