# Generated by Django 5.1.6 on 2025-06-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_threshold_tax_delete_tax_delete_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
