# Generated by Django 5.1.6 on 2025-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_profile_facebook_alter_profile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='About',
            field=models.TextField(blank=True, max_length=130, null=True),
        ),
    ]
