# Generated by Django 5.1.6 on 2025-10-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='CountryCode1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='CountryCode2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
